
solver:
  num_workers: 8
  batch_size: 128
  epochs: 200
  lr: 0.05
  es_patience: 100
  device: 'cuda'
  scheduler: 'none'
  factor: 0.5
  patience: 3
  T_max: 20


# model
model:
  name: 'convlstm'
  hidden_size: 256
  num_layers: 2
  dropout: 0.3
  output_size: 6


