
setting: 'mtl'
# model
model:
  name: 'lstmext'
  hidden_size: 64
  num_layers: 2
  dropout: 0.3
  output_size: 6

solver:
  num_workers: 8
  batch_size: 128
  epochs: 300
  lr: 0.05
  es_patience: 200
  device: 'cuda'
  scheduler: 'none'
  factor: 0.5
  patience: 3
  min_lr: 0.00225

loss:
  weights: [0.96, 0.98, 0.95, 0.94, 0.85, 0.65]

