
solver:
  num_workers: 8
  batch_size: 256
  epochs: 200
  lr: 0.01
  es_patience: 50
  device: 'cuda'

# model
model:
  name: 'lstm'
  hidden_size: 64
  num_layers: 1
  dropout: 0.3
  output_size: 6

