
setting: 'multimodal'

tasks: ['t1']
# model
model:
  name: 'multimodal'
  output_size: 1
  cache_dir: '/tmp/'
  

solver:
  num_workers: 1
  batch_size: 30
  epochs: 50
  lr: 1e-3
  es_patience: 15
  device: 'cuda'
  optimizer: 'sgd'
  scheduler: 'cosine'
  factor: 0.5
  min_lr: 3e-5
  log_steps: 30
  eval_steps: 60

  validate_on: 'loss'
  validate_mode: 'min'

data:
  name: 'bau'
  annotation: "V"
  aggregate: True
  annotator: "bau"
  split_strategy: "labels"
  label_path: "outputs/fluencybank/dataset/stutter_hf/label_split/bau_multimodal_"
  root: "datasets/fluencybank/ds_label/reading/A3/clips/video/"