tasks: ['t2']
# model
model:
  name: 'whisperyoho'
  hidden_size: 64
  num_layers: 2
  dropout: 0.3
  output_size: 6
  input_size: 40

solver:
  num_workers: 8
  batch_size: 8
  epochs: 100
  lr: 0.01
  es_patience: 100
  device: 'cuda'
  scheduler: 'plateau'
  factor: 0.5
  patience: 50
  min_lr: 1e-5
  losses: ['yoho']
  log_steps: 20
  eval_steps: 20

loss:
  # weights: [0.96, 0.98, 0.95, 0.94, 0.8, 0.4] # weights for bce loss
  alpha: [0.96, 0.96, 0.96, 0.96, 0.7, 0.6] # alpha for focal loss
  reduction: 'mean'
  gamma: 2

