tasks: ['t2']
setting: 'sed'
# model
model:
  name: 'sednet'
  encoder_name: 'wav2vec2-b'
  emb_dim: 768
  hidden_size: 64
  num_layers: 2
  dropout: 0.3
  output_size: 6
  input_size: 40

solver:
  num_workers: 8
  batch_size: 32
  epochs: 100
  lr: 0.001
  es_patience: 30
  device: 'cuda'
  scheduler: 'plateau'
  factor: 0.5
  patience: 10
  min_lr: 1e-5
  losses: ['sed']
  log_steps: 20
  eval_steps: 20

loss:
  weights: [7.29, 9.23, 27.94, 3.96, 2.268] # weights for bce loss


